;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Nov 28 2016
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================


.org 0x00
	jmp rst_isr
.org 0x12
	jmp timer0_ovf

timer0_ovf:
	cli
	
	sei
	ret
	
rst_isr:
	cli
	ldi r16, (1 << TOIE0) ;enable timer0_ovf
	out TIMSK, r16
	ldi r16, (1 << wgm00 | 1 << wgm01 | 1 << CS00 | 0 << CS01 | 1 << CS02 | 0 << COM00 |  1 << COM01)
	out TCCR0, r16
	ldi r16, (0 << PD6 | 0 << PD7)
	out DDRD, r16
	ldi r16, (1 << PB3)
	out DDRB, r16
	cbi PORTB, 3
	sbi PIND, 6
	sbi PIND, 7
	sei
	
	

start:
	sbic PIND, 7
	jmp on_PD6
	ldi r20, 0x7F
	out OCR0, r20
	sbi PORTB, 3
	jmp end
on_PD6:	
	sbic PIND, 6
	jmp end
	ldi r20, 0xFE
	out OCR0, r20
	sbi PORTB, 3
end:	
	jmp start


;====================================================================
