;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Nov 19 2016
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

.org 0x00
	jmp rst_isr

rst_isr:
	CLI
	CLR  R16
	OUT  EECR,R16

.MACRO __DELAY_USW
	LDI  R24,LOW(@0)
	LDI  R25,HIGH(@0)
__DELAY_USW_LOOP:
	SBIW R24,1
	BRNE __DELAY_USW_LOOP
	.ENDM

start:
	ldi r16, (0 << PD3)
	out DDRD, r16
	ldi r16, (1 << PD5) 
	out DDRD, r16
	ldi r16, (1 << PD3)
	out PIND, r16
while1:
	SBIC 0x10,3
	rjmp off
	ldi r17, 0x0A
	ldi r18, 0x00
for1:
	cp r17,r18
	breq while1
	inc r18
	SBI 0x12,5
	LDI  R26,LOW(500)
	LDI  R27,HIGH(500)
	call delay_ms
	cbi 0x12,5
	LDI  R26,LOW(500)
	LDI  R27,HIGH(500)
	call delay_ms
	rjmp for1
off:
	cbi 0x12,5
	rjmp while1
	jmp start

delay_ms:
	adiw r26,0
	breq __delay_ms1
__delay_ms0:
	__DELAY_USW 0xFA
	wdr
	sbiw r26,1
	brne __delay_ms0
__delay_ms1:
	ret

;====================================================================
