;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Nov 28 2016
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

.def count = r20
.def round = r21
.org 0x00
	jmp rst_isr
.org 0x12
	jmp timer0_ovf

timer0_ovf:
	cli
	inc count
	cpi count, 0x04
	brne end
	ldi count, 0x00
	cpi round, 0x00
	brne odd
even:
	sbi PORTD, 4
	cbi PORTD, 5
	ldi round, 0x01
	jmp end
	
odd:
	cbi PORTD, 4
	sbi PORTD, 5
	ldi round, 0x00
	
end:
	sei
	ret
	
rst_isr:
	cli
	ldi count, 0x00
	ldi round, 0x00
	ldi r16, (1 << TOIE0) ;enable timer0_ovf
	out TIMSK, r16
	ldi r16, (0 << wgm00 | 0 << wgm01 | 1 << CS00 | 0 << CS01 | 1 << CS02);normal mode, prescaler1024
	out TCCR0, r16
	ldi r16, (1 << PD4 | 1 << PD5)
	out DDRD, r16
	sei
	
	

start:
	
	jmp start


;====================================================================
