;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Nov 28 2016
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

.def count = r20
.def round = r21
.org 0x00
	jmp rst_isr
.org 0x26
	jmp timer0_comparematch

timer0_comparematch:
	cli
	inc count
	cpi count, 0x01
	brne end
	ldi count, 0x00
	cpi round, 0x00
	brne off
on:
	sbi PORTB, 3 
	ldi round, 0x01
	jmp end
	
off:
	cbi PORTB, 3
	ldi round, 0x00
	
end:
	sei
	ret
	
rst_isr:
	cli
	ldi count, 0x00
	ldi round, 0x00
	ldi r16, 0xFF
	out OCR0, r16
	ldi r16, (1 << OCIE0) ;enable timer0_cmpmatch
	out TIMSK, r16
	ldi r16, (0 << wgm00 | 1 << wgm01 | 1 << CS00 | 0 << CS01 | 1 << CS02);ctc mode, prescaler 1024
	out TCCR0, r16
	ldi r16, (1 << PB3)
	out DDRB, r16
	sei
	
	

start:
	
	jmp start


;====================================================================
